import "./globals.css";
import {Jersey_10} from "next/font/google"
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
 const roboto = Jersey_10({
   weight: "400",
   subsets: ["latin"],
 })
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className} >
       
        <Navbar/>
        {children}</body>
    </html>
  );
}
